Revert "(@cladmi) PROPOSAL: fix dtls_config.h not visible in all headers"
This reverts commit 5bd3fd43701fc7dda8fcd2605ede2c0282bdba8d.

For RIOT, this bring some issues:

    In function `add_auth_data':
    ccm.c:(.text.add_auth_data+0x80): undefined reference to `assert'
    collect2: error: ld returned 1 exit status